# Generated by Django 5.0 on 2024-01-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('slug', models.CharField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('year', models.CharField()),
                ('album_type', models.CharField(choices=[('SINGLE', 'Single'), ('COMPILATION', 'Compilation'), ('ALBUM', 'Album')], max_length=11)),
                ('artist', models.ManyToManyField(to='spotify.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='spotify.genre'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('duration', models.IntegerField()),
                ('album', models.ManyToManyField(to='spotify.album')),
                ('artist', models.ManyToManyField(to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ListenLog',
            fields=[
                ('played_at_posix_timestamp', models.CharField(primary_key=True, serialize=False)),
                ('played_at_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('played_at_dow', models.CharField(choices=[(6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('played_at_hour', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.track')),
            ],
        ),
    ]
