# Generated by Django 5.0 on 2024-01-11 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenlog',
            name='played_at_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 0, 20, 47, 871446, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
