# Generated by Django 5.0 on 2024-01-11 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_listenlog_played_at_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenlog',
            name='played_at_dow',
        ),
        migrations.RemoveField(
            model_name='listenlog',
            name='played_at_hour',
        ),
        migrations.RemoveField(
            model_name='listenlog',
            name='played_at_month',
        ),
    ]
