# Generated by Django 5.0 on 2024-01-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_listenlog_played_at_dow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenlog',
            name='album',
        ),
    ]
