# Generated by Django 5.0 on 2024-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_remove_listenlog_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='photo',
            new_name='image_large',
        ),
        migrations.RenameField(
            model_name='listenlog',
            old_name='played_at_posix_timestamp',
            new_name='posix_tmstmp',
        ),
        migrations.AddField(
            model_name='album',
            name='image_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image_medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_small',
            field=models.URLField(blank=True, null=True),
        ),
    ]
