# Generated by Django 5.0 on 2024-01-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_photo_artist_image_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
