# Generated by Django 5.0 on 2024-01-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_genre_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre',
            new_name='genres',
        ),
    ]
