# Generated by Django 5.0 on 2024-01-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_rename_genre_artist_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
