# Generated by Django 5.0 on 2024-01-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_rename_artist_album_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='spotify.genre'),
        ),
    ]
