# Generated by Django 5.0 on 2024-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_alter_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(),
        ),
    ]
