# Generated by Django 5.0 on 2024-02-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_alter_album_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='image_large',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_medium',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_small',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spotify.genrefamily'),
        ),
    ]
