# Generated by Django 5.0 on 2024-02-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_genrefamily_alter_album_image_large_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenlog',
            old_name='track',
            new_name='track_played',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_family',
        ),
        migrations.CreateModel(
            name='TrackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify.listenlog')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify.track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='logs',
            field=models.ManyToManyField(through='spotify.TrackLog', to='spotify.listenlog'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_family',
            field=models.ManyToManyField(null=True, to='spotify.genrefamily'),
        ),
    ]
