# Generated by Django 5.0 on 2024-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_rename_track_listenlog_track_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_family',
            field=models.ManyToManyField(to='spotify.genrefamily'),
        ),
    ]
