# Generated by Django 5.0 on 2024-02-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0014_alter_genre_genre_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='logs',
        ),
    ]
