# Generated by Django 5.0 on 2024-02-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0015_remove_track_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_family',
            field=models.ManyToManyField(blank=True, to='spotify.genrefamily'),
        ),
    ]
